global:
  scrape_interval: 5s

scrape_configs:
- job_name: blackbox 
  metrics_path: /metrics
  static_configs:
    - targets:
      - localhost:9115  

- job_name: blackbox-http 
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
       - http://52.67.8.223:8080
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: localhost:9115 